# Generated by Django 4.2.5 on 2023-10-08 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0004_user_is_activated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_activated",
        ),
    ]
