# Generated by Django 4.2.6 on 2023-10-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phase_two", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
