# Generated by Django 4.2.6 on 2023-10-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phase_two", "0003_item_created_at_alter_item_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="username",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
