# Generated by Django 4.2.6 on 2023-10-30 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("phase_two", "0004_item_username_alter_item_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=255)),
                ("item_id", models.IntegerField(default=0)),
                ("rating", models.CharField(default="", max_length=255)),
                ("comment", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
