# Generated by Django 4.2.6 on 2023-10-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("phase_two", "0005_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="item_id",
        ),
        migrations.AddField(
            model_name="review",
            name="item",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="phase_two.item",
            ),
        ),
    ]
