# Generated by Django 4.2.6 on 2023-10-31 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phase_two", "0006_remove_review_item_id_review_item"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Review",
            new_name="Comment",
        ),
    ]
